spring:
  application:
    name: nacos-mcp
  ai:
    mcp:
      server:
        name: webmvc-mcp-server
        version: 1.0.0
        type: SYNC

    alibaba:
      mcp:
        nacos:
          server-addr: http://127.0.0.1:8848
          namespace: public
          username: coderpwh_admin
          password: coderpwh_admin
          registry:
            enabled: true

server:
  port: 9081