spring:
  application:
    name: spring-ai-alibaba-rag-milvus-example

  ai:
    dashscope:
      api-key:

    vectorstore:
      milvus:
        client:
          host: localhost # default: localhost
          port: 19530 # default: 19530
          username: root # default: root
          password: milvus # default: milvus

        databaseName: default  # default: default
        collectionName: vector_store # default: vector_store
        embeddingDimension: 1536 # default: 1536
        indexType: IVF_FLAT # default: IVF_FLAT
        metricType: COSINE # default: COSINE